
GET http://localhost:3000/routes

###
GET http://localhost:3000/routes/1

###
DELETE http://localhost:3000/routes/64e95284f839260d092436d8

###
POST http://localhost:3000/routes
Content-Type: application/json

{
    "name": "Franco for Guarulhos",
    "source_id": "EjxBdi4gZGEgU2F1ZGFkZSwgMzE1LCBGcmFuY28gZGEgUm9jaGEgLSBTUCwgMDc4NTMtMDMwLCBCcmFzaWwiMRIvChQKEgmvrj3CN-TOlBF_6A1kRPGz2xC7AioUChIJ1TMJJTXkzpQRgZzf9BkffRs",
    "destination_id": "ChIJ0TqRrzyJzpQRbXnRhkTfVgI"
}

### Googles Maps
### Pegar o place ID
GET http://localhost:3000/places?text=av doutor presidente dutra , 3150

### Pegar direções entre dois pontos
GET http://localhost:3000/directions?originId=EjxBdi4gZGEgU2F1ZGFkZSwgMzE1LCBGcmFuY28gZGEgUm9jaGEgLSBTUCwgMDc4NTMtMDMwLCBCcmFzaWwiMRIvChQKEgmvrj3CN-TOlBF_6A1kRPGz2xC7AioUChIJ1TMJJTXkzpQRgZzf9BkffRs&destinationId=ChIJ0TqRrzyJzpQRbXnRhkTfVgI
