version: '3'

services:
  app:
    container_name: car-simulator-api
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
    networks:
      - network1
    # extra_hosts:
    #   - "host.docker.internal:172.17.0.1"
  redis:
    image: redis:latest
    container_name: redis
    networks:
      - network1

volumes:
  mongodb_data:
    driver: local

networks:
  network1:
    name: car-simulator-kafka_internal-kafka-network
    external: true
